version: '3.4'

services:
  bugsDb:
   image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
   environment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: "myPass123"
    MSSQL_PID: Express
   ports: 
    - "1433:1433"

  bugsapi:
   ports:
    - "8080:80"
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   build:
    context: ./BugSystem
    dockerfile: Dockerfile
  
  frontend:
   ports:
    - "5050:80"
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   build:
    context: ./frontend
    dockerfile: Dockerfile
